version: '3.8'

services:
  app:
    image: ${{ secrets.DOCKER_USERNAME }}/market_normalization:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/normalization
      SPRING_DATASOURCE_USERNAME: produser
      SPRING_DATASOURCE_PASSWORD: prodpass
      SPRING_REDIS_HOST: redis
    depends_on:
      - db
      - redis
    restart: always

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: prodroot
      MYSQL_DATABASE: proddb
      MYSQL_USER: produser
      MYSQL_PASSWORD: prodpass
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

volumes:
  db-data:
