name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]    #  CI가 성공한 후 트리거됨
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: "${{ secrets.EC2_SSH_KEY }}"
          envs: DB_USERNAME,DB_PASSWORD,DB_ROOT_PASSWORD
          command_timeout: 2m
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/market_normalization:latest                              # 도커 허브에서 이미지 땡기기
            docker tag ${{ secrets.DOCKER_USERNAME }}/market_normalization:latest market_normalization:latest  # 로컬 태그 변경
            
            docker-compose -f docker-compose.yml up -d                                                   # 새 컨테이너 배포
            
 
