name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]    #  CI가 성공한 후 트리거됨
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/market_normalization:latest  # 도커 허브에서 이미지 땡기기
            docker-compose -f docker-compose.prod.yml down                          # 기존 컨테이너 종료
            docker-compose -f docker-compose.prod.yml up -d                         # 새 컨테이너 배포
