name: CI Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions에서 제공하는 가상 머신

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 코드 가져오기

      - name: Set up JDK 17
        uses: actions/setup-java@v3  # JDK 17 셋업
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build Application
        run: ./gradlew build

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/market_normalization:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/market_normalization:latest

      - name: Debugging
        run: |
          pwd
          ls -al
          java -version
          docker-compose logs   # Docker 컨테이너 로그 확인

