name: CI Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions에서 제공하는 가상 머신

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 코드 가져오기

      - name: Set up JDK 17
        uses: actions/setup-java@v3  # JDK 17 설치
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew  # Gradle 실행 권한 부여

      - name: Build with Gradle
        run: ./gradlew build  # 프로젝트 빌드

      - name: Run tests
        run: ./gradlew test  # 테스트 실행

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t market_normalization:latest . 
          docker push market_normalization:latest

      - name: Debugging #디버깅용 로그 출력
        run: |
          pwd
          ls -al
          java -version
